# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  username: cstewart
  password:
  encoding: unicode
  database: userpractice_development
  pool: 5
  host: localhost

test:
  adapter: postgresql
  username: cstewart
  password:
  encoding: unicode
  database: userpractice_test
  pool: 5
  host: localhost
